name: 'MongoDB in GitHub Actions'
description: 'Start a MongoDB server (on default port 27017 or a custom port)'

branding:
  icon: 'database'
  color: 'green'

inputs:
  mongodb-image:
    description: 'MongoDB image to use (defaults to using "mongo" from Docker Hub but you could also use an image from another repository such as Amazons "public.ecr.aws/docker/library/mongo")'
    required: false
    default: 'mongo'

  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  mongodb-replica-set:
    description: 'MongoDB replica set name (no replica set by default)'
    required: false
    default: ''

  mongodb-port:
    description: 'MongoDB port to use (default 27017)'
    required: false
    default: 27017

  mongodb-db:
    description: 'MongoDB db to create (default: none)'
    required: false
    default: ''

  mongodb-username:
    description: 'MongoDB root username (default: none)'
    required: false
    default: ''

  mongodb-password:
    description: 'MongoDB root password (default: none)'
    required: false
    default: ''

  mongodb-container-name:
    description: 'MongoDB container name (default: "mongodb")'
    required: false
    default: 'mongodb'

  mongodb-key:
    description: 'MongoDB key, required if replica set and auth are setup through username and password (no key set by default)'
    required: false
    default: ''

  mongodb-authsource:
    description: 'MongoDB authenticationDatabase a.k.a authSource to use (default: "admin" based on https://github.com/docker-library/mongo/blob/master/8.0/docker-entrypoint.sh#L372C4-L372C20)'
    required: false
    default: 'admin'

  docker-network:
    description: 'Docker network to attach the MongoDB container to. If not provided, will try to use the default GitHub Actions network if available (github_network_<rand>).'
    required: false
    default: ''

  docker-network-alias:
    description: 'Network alias for the MongoDB container when attaching to a Docker network. If not provided, will use mongodb-container-name input'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongodb-image }}
    - ${{ inputs.mongodb-version }}
    - ${{ inputs.mongodb-replica-set }}
    - ${{ inputs.mongodb-port }}
    - ${{ inputs.mongodb-db }}
    - ${{ inputs.mongodb-username }}
    - ${{ inputs.mongodb-password }}
    - ${{ inputs.mongodb-container-name }}
    - ${{ inputs.mongodb-key }}
    - ${{ inputs.mongodb-authsource }}
    - ${{ inputs.docker-network }}
    - ${{ inputs.docker-network-alias }}
  post-entrypoint: /stop-mongodb.sh
